import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { ShopContextProvider } from "@/context/ShopContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ShopContextProvider>
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
       </ShopContextProvider>
      </body>
    </html>
  );
}
